services:
  - type: web
    name: cocwebsite-server
    runtime: node
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
